import type { ToonTemplateDefinition, ToonTemplateId } from './toon-types'

export const TOON_TEMPLATES: Record<ToonTemplateId, ToonTemplateDefinition> = {
  'comparison-board': {
    id: 'comparison-board',
    label: 'Comparison board',
    layoutGrammar: 'two balanced columns or two opposing blocks with a clear comparison spine',
    elementGrammar: ['title block', 'left entity card', 'right entity card', 'comparison rows', 'highlight badge'],
    textGrammar: ['short row labels', 'symmetry over prose', 'two to six comparison rows'],
    colorGrammar: ['left entity', 'right entity', 'contrast highlight', 'warning accent'],
    compositionGrammar: ['symmetry', 'clear row alignment', 'fast left-right scanning'],
    localRules: ['avoid extra pathways', 'avoid more than two main entities'],
  },
  timeline: {
    id: 'timeline',
    label: 'Timeline',
    layoutGrammar: 'horizontal progression rail with grouped stages or phase bands',
    elementGrammar: ['title block', 'timeline node', 'phase band', 'inflection marker', 'endpoint'],
    textGrammar: ['tiny stage labels', 'few phase names', 'timing grouped not repeated'],
    colorGrammar: ['early phase', 'middle phase', 'late phase', 'alert marker'],
    compositionGrammar: ['directional flow', 'clear sequencing', 'minimal branching'],
    localRules: ['avoid dense mechanism inserts', 'avoid floating icons without phase anchors'],
  },
  cascade: {
    id: 'cascade',
    label: 'Cascade flow',
    layoutGrammar: 'trigger-to-consequence flow with one or two controlled branches',
    elementGrammar: ['trigger node', 'intermediate node', 'branch connector', 'outcome node', 'warning endpoint'],
    textGrammar: ['cause and effect labels only', 'short consequence phrases', 'no narrative captions'],
    colorGrammar: ['trigger', 'mechanism', 'complication', 'danger endpoint'],
    compositionGrammar: ['dominant start point', 'causal arrows', 'branch restraint'],
    localRules: ['avoid unrelated side stories', 'avoid too many branches'],
  },
  'risk-map': {
    id: 'risk-map',
    label: 'Risk map',
    layoutGrammar: 'central hub with grouped incoming factors or surrounding contributor clusters',
    elementGrammar: ['center concept', 'risk badge', 'group label', 'inward connector', 'caution cluster'],
    textGrammar: ['badge labels', 'short group names', 'no bullet list paragraphs'],
    colorGrammar: ['central driver', 'modifiable risks', 'nonmodifiable risks', 'high-risk accent'],
    compositionGrammar: ['outside-in scanning', 'clear grouping', 'balanced spacing'],
    localRules: ['avoid flat unordered lists', 'avoid mechanism panels'],
  },
  'protocol-board': {
    id: 'protocol-board',
    label: 'Protocol board',
    layoutGrammar: 'ordered step blocks or converging regimen modules with one therapeutic path',
    elementGrammar: ['title block', 'step block', 'drug block', 'checkpoint node', 'contraindication badge'],
    textGrammar: ['few step names', 'tiny action labels', 'no long regimen prose'],
    colorGrammar: ['treatment step', 'checkpoint', 'supporting measure', 'caution badge'],
    compositionGrammar: ['clear order', 'shared outcome emphasis', 'low branching unless required'],
    localRules: ['avoid unrelated disease natural history', 'avoid overstuffed toxicity strips'],
  },
  'mechanism-board': {
    id: 'mechanism-board',
    label: 'Mechanism board',
    layoutGrammar: 'single site-of-action strip or one focused before-and-after mechanism scene',
    elementGrammar: ['site icon', 'drug block', 'target node', 'effect arrow', 'outcome node'],
    textGrammar: ['one target label', 'one action label', 'one effect label'],
    colorGrammar: ['target', 'drug action', 'blocked process', 'clinical effect'],
    compositionGrammar: ['single dominant scene', 'left-to-right change', 'minimal side information'],
    localRules: ['avoid multi-path pathway maps', 'avoid secondary mechanisms unless central'],
  },
}

